version: "3.4"
# https://docs.docker.com/compose/compose-file/
services:
  encuesta-nginx:
    image: nginx:latest
    container_name: encuesta-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/security-headers.conf:/etc/nginx/security-headers.conf
      - ./nginx/sites/encuesta.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
    networks:
      - encuesta-network

  # NestJs      
  encuesta-nestjs:
    container_name: encuesta-nestjs
    build:
      context: ./data/back-node
      dockerfile: Dockerfile
    volumes:
      - ./data/back-node:/usr/src/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    networks:
      encuesta-network:
        aliases:
            - encuesta-back-node

  ## PGL
  encuesta-pgl:
    image: postgres:latest
    container_name: encuesta-pgl
    env_file: ./build/pgl/pgl.env
    ports:
      - "5437:5432"
    volumes:
      - ./db/pgl/data:/var/lib/postgresql/data
    restart: "unless-stopped"
    networks:
      encuesta-network:
        aliases:
          - encuesta-pgl-db
  
  encuesta-pgl-test:
    image: postgres:latest
    command: sh -c "psql -h encuesta-pgl-db -U postgres -d encuesta"
    networks:
      - encuesta-network
    depends_on:
      - encuesta-pgl
    environment:
      PGUSER: postgres
      PGDATABASE: encuesta
    stdin_open: true
    tty: true

networks:
  encuesta-network: