version: "3.4"
# https://docs.docker.com/compose/compose-file/
services:
  #encuesta-nginx:
  #  image: nginx:latest
  #  container_name: encuesta-nginx
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #    - ./nginx/security-headers.conf:/etc/nginx/security-headers.conf
  #    - ./nginx/sites/encuesta.conf:/etc/nginx/conf.d/default.conf
  #  ports:
  #    - 80:80
  #  restart: always
  #  networks:
  #    - encuesta-network

  encuesta-nextapp:
    container_name: encuesta-nextapp
    image: encuesta-nextapp
    build:
      context: ./build/next
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./data/encuesta-front:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    restart: "always"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "0.5"
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    networks:
      encuesta-network:
        aliases:
          - encuesta-nextapp-node

  # NestJs      
  encuesta-nestjs:
    container_name: encuesta-nestjs
    build:
      context: ./data/encuesta-node
      dockerfile: Dockerfile
    volumes:
      - ./data/encuesta-node:/usr/src/app
    command: npm run start:dev
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    depends_on:
      - encuesta-pgl
    networks:
      encuesta-network:
        aliases:
          - encuesta-back-node

  ## PGL
  encuesta-pgl:
    image: postgres:16.0
    container_name: encuesta-pgl
    env_file: ./build/pgl/pgl.env
    ports:
      - "5437:5432"
    volumes:
      - ./db/pgl/data:/var/lib/postgresql/data
      - ./build/pgl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "unless-stopped"
    networks:
      encuesta-network:
        aliases:
          - encuesta-pgl-db

  encuesta-validator:
    container_name: encuesta-validator
    build:
      context: ./
      dockerfile: build/flask/Dockerfile
    restart: "unless-stopped"
    ports:
      - "5000:5000"
    env_file: ./build/flask/flask.env
    command: flask run --host=0.0.0.0
    volumes:
      - ./data/encuesta-validator:/var/www/encuesta-validator
    networks:
      encuesta-network:
        aliases:
          - encuesta-validator

networks:
  encuesta-network:
